site_name: MDE Docs

theme:
  name: material
  logo: assets/site-files/mde-logo.png
  favicon: assets/site-files/favicon.ico
  palette: 
    - scheme: default
      primary: light blue
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: light blue
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - content.code.copy
    - content.tabs.link

extra_css:
  - stylesheets/extra.scss

plugins:
  - git-revision-date-localized:
      strict: false
      fallback_to_build_date: true
  - search:
      lang: en

use_directory_urls: false

nav:
  - Home: 'index.md'
  - Model Transformation Languages:
    - ETL: 'etl.md'
    - YAMTL: 'yamtl.md'
  - Examples:
    - Linked List Reversal: 'examples/linked-list-reversal-example.md'
    - Flowchart to HTML: 'examples/flowchart-to-html-example.md'


markdown_extensions: 
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - footnotes
