site_name: MDE Docs

theme:
  name: material
  logo: assets/site-files/mde-logo.png
  favicon: assets/site-files/favicon.ico
  palette: 
    - scheme: default
      primary: light blue
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    
    - scheme: slate
      primary: light blue
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

  features:
    - content.code.copy

plugins:
  - git-revision-date-localized:
      strict: false
      fallback_to_build_date: true
  - search:
      lang: en

nav:
  - Home: 'index.md'
  - Model Transformation Languages:
    - ETL: 'etl.md'
    - YAMTL: 'yamtl.md'
  - Examples:
    - Linked List Reversal: 'examples/linked-list-reversal-example.md'


markdown_extensions: 
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format